DATABASE_URI = "mongodb://localhost:27017/Transaction"

MODEL_PATH = r'C:\Users\jitenderkumar\Documents\Python WebServices\Transactions Project\Model\cv_sgd_model.sav'
SEARCH_FILE = r'C:\Users\jitenderkumar\Documents\Python WebServices\Transactions Project\Excel_Data\card_txn_201604_201606_masked.csv'


CLASS1 = 'kno-rdesc'
CLASS2 = 'st'

MAPPING = {
  "txn" : "Transaction",
  "txn_s" : "transaction_source",
  "dc" : "debit_credit",
  "txn_d" : "TRANS_DESC",
  "st" : "source_type",
  "mt" : "Manual Tag"
}



MATCHES = {
        "spotify" : "Spotify",
        "salary" : "Salary",
        "salaries" : "Salary",
        "payroll" : "Salary",
        "income" : "Wages",
        "incom" : "Wages",
        "wage" : "Wages",
        "wages" : "Wages",
        "wag e" : "Wages",
        "rent" : "RENT RELATED",
        "bill" : "UTILITIES",
        "bills" : "UTILITIES",
        "insur" : "INSURANCE RELATED",
        "insurance" : "INSURANCE RELATED",
        "tax" : "TAX RELATED",
        "loan" : "LOAN RELATED",
        "mortgage" : "LOAN RELATED",
        "support" : "Benefits",
        "internet" : "UTILITIES-PHONE/INTERNET",
        "inter et" : "UTILITIES-PHONE/INTERNET",
        "stuff" : "UTILITIES-PHONE/INTERNET",
        "stuff fibre" : "UTILITIES-PHONE/INTERNET",
        "my republic" : "UTILITIES-PHONE/INTERNET",
        "myrepublic" : "UTILITIES-PHONE/INTERNET",
        "spark" : "UTILITIES-PHONE/INTERNET",
        "slingshot" : "UTILITIES-PHONE/INTERNET",
        "orcon" : "UTILITIES-PHONE/INTERNET",
        "degrees" : "UTILITIES-PHONE/INTERNET",
        "two degree" : "UTILITIES-PHONE/INTERNET",
        "actrix" : "UTILITIES-PHONE/INTERNET",
        "compass" : "UTILITIES-PHONE/INTERNET",
        "worldnet" : "UTILITIES-PHONE/INTERNET",
        "NZfarming" : "UTILITIES-PHONE/INTERNET",
        "nz farming" : "UTILITIES-PHONE/INTERNET",
        "vodafone" : "UTILITIES-PHONE/INTERNET",
        "woosh" : "UTILITIES-PHONE/INTERNET",
        "ultrafast" : "UTILITIES-PHONE/INTERNET",
        "ultra fast" : "UTILITIES-PHONE/INTERNET",
        "wireless" : "UTILITIES-PHONE/INTERNET",
        "call plus" : "UTILITIES-PHONE/INTERNET",
        "callplus" : "UTILITIES-PHONE/INTERNET",
        "farmside" : "UTILITIES-PHONE/INTERNET",
        "kiwilink" : "UTILITIES-PHONE/INTERNET",
        "inspire" : "UTILITIES-PHONE/INTERNET",
        "now broad" : "UTILITIES-PHONE/INTERNET",
        "now intern" : "UTILITIES-PHONE/INTERNET",
        "bigpipe" : "UTILITIES-PHONE/INTERNET",
        "clearnet" : "UTILITIES-PHONE/INTERNET",
        "electricity" : "UTILITIES -POWER/GAS",
        "powershop" : "UTILITIES -POWER/GAS",
        "electric kiwi" : "UTILITIES -POWER/GAS",
        "electrickiwi" : "UTILITIES -POWER/GAS",
        "flick" : "UTILITIES -POWER/GAS",
        "energyonline" : "UTILITIES -POWER/GAS",
        "energy online" : "UTILITIES -POWER/GAS",
        "nova" : "UTILITIES -POWER/GAS",
        "pulse" : "UTILITIES -POWER/GAS",
        "pulseenergy" : "UTILITIES -POWER/GAS",
        "pulse energy" : "UTILITIES -POWER/GAS",
        "meridian" : "UTILITIES -POWER/GAS",
        "mercury" : "UTILITIES -POWER/GAS",
        "genesis" : "UTILITIES -POWER/GAS",
        "contact" : "UTILITIES -POWER/GAS",
        "globug" : "UTILITIES -POWER/GAS",
        "trust power" : "UTILITIES -POWER/GAS",
        "trustpower" : "UTILITIES -POWER/GAS",
        "trust" : "UTILITIES -POWER/GAS",
        "gem" : "SHOPPING",
        "gem visa" : "SHOPPING",
        "q card" : "SHOPPING",
        "serious saver" : "INTERNAL_TRANSFER",
        "serious" : "INTERNAL_TRANSFER",
        "go" : "INTERNAL_TRANSFER",
        "online account" : "INTERNAL_TRANSFER",
        "low rate visa" : "INTERNAL_TRANSFER",
        "kiwisaver" : "INTERNAL_TRANSFER",
        "medic" : "HEALTH/MEDICAL",
        "medical" : "HEALTH/MEDICAL",
        "hospital" : "HEALTH/MEDICAL",
        "chemist" : "HEALTH/MEDICAL",
        "pharma" : "HEALTH/MEDICAL",
        "doctor" : "HEALTH/MEDICAL",
        "credit card" : "CC PAYMENT",
        "uber" : "TRANSPORT RELATED",
        "taxi" : "TRANSPORT RELATED",
        "netflix" : "ONLINE VIDEOS",
        "amazon" : "ONLINE RETAIL",
        "alibaba" : "ONLINE RETAIL",
        "grocer" : "GROCERY",
        "ministry of justice" : "GOVERNMENT SERVICES",
        " rent " : "RENT",
        "new world" : "SHOPPING",
        "air new zealand" : "AIR TRANSPORT",
        "air newzealand" : "AIR TRANSPORT",
        "qantas" : "AIR TRANSPORT",
        "jetstar" : "AIR TRANSPORT",
        "virgin" : "AIR TRANSPORT",
        "airbnb" : "ACCOMODATION",
        "booking" : "ACCOMODATION",
        "agoda" : "ACCOMODATION",
        "wotif": "ACCOMODATION",
        "orbitremit" : "REMITTANCE",
        "orbit" : "REMITTANCE"
}
